config/routes.rb
QueryComposer::Application.routes.draw do

  post "scheduled_jobs/batch_query", :constraints => {:ip => /127.0.0.1/}

  devise_for :users

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  
  get "endpoints/refresh_endpoint_statuses"
  post 'queries/generate_query'

  resources :endpoints
  resources :library_functions
  resources :template_queries

  post "queries/clone_template"
  resources :queries do
    member do
      post 'execute'
      delete 'destroy'
      get 'log'
      get 'refresh_execution_results'
      get 'execution_history'
      get 'cancel'
      get 'cancel_execution'
      get 'builder'
      get 'builder_simple'
      get 'edit_code'
      get 'result'
    end
    collection do
      post 'execute_batch'
    end
  end
  
  
  resources :code_sets do

  end
  
  namespace :code_sets do
    get "by_type/:type", :action=>:by_type
  end
  
  root :to => 'queries#index'

  

end

app/models/library_function.rb
class LibraryFunction
  include Mongoid::Document

  belongs_to :user

  validates_presence_of :name, :definition

  field :name, type: String
  field :definition, type: String

end

app/controllers/library_functions_controller.rb
class LibraryFunctionsController < ApplicationController
  load_resource exclude: %w{index}
  authorize_resource
  before_filter :authenticate_user!

  # add breadcrumbs
  add_breadcrumb 'Library Functions', :library_functions_url
  add_breadcrumb_for_resource :library_function, :name, only: %w{edit show log execution_history}
  add_breadcrumb_for_actions only: %w{edit new}

  creates_updates_destroys :library_function

  def index
    @library_functions = (current_user.admin?) ? LibraryFunction.all : current_user.library_functions
  end

  def new
    @library_function.definition = "function<name>(<params>) {
    
    }\r\n"
  end

  def before_create
    @library_function.user = current_user
  end

end

app/helpers/library_functions_helper.rb
module LibraryFunctionsHelper
end

app/views/library_functions/_form.html.erb
<% content_for :head do -%>
  <%= stylesheet_link_tag "debugger.css"%>
  <%= javascript_include_tag "ace_editor/ace" %>
  <%= javascript_include_tag "ace_editor/mode-javascript" %>

   

  <script type="text/javascript">
    $(document).ready(function() {
      hDebugger.initializeEditor('library_function', ['library_function']);
      
      hDebugger.showCodeIsValid = function() {
    	  $('#submit_button').removeAttr('disabled');
    	};
    	hDebugger.showCodeIsInvalid = function() {
    	  $('#submit_button').attr('disabled', 'disabled');
    	};
    	
    	hDebugger.debug(['library_function']);
    });
  </script>

<% end %>

<%= simple_form_for(@library_function) do |f| %>
  <%= f.error_notification %>
  
  <table class="simpleTable">
    <tr>
      <th>Name</th>
      <td><%= f.input_field :name, :class=> "entryField" %></td>
    </tr>
    <tr>
      <th>Definition</th>
      <td>
        <div id="library_function_container" class="debug_container entryField">
          <div id="library_function_editor" class="debug_editor entryField"></div>
          <textarea id="library_function_text" name="library_function[definition]" class="hidden"><%= @library_function[:definition] %></textarea>
        </div>
        <div id="library_function_error_panel" class="debug_error_panel">
            <p id="library_function_error_panel_text"></p>
        </div>
      </td>
    </tr>
  </table>
  
  <%= f.button :submit, :id => 'submit_button', :class => 'btn primary m' %>
<% end %>

app/views/library_functions/edit.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {library_functions: true}} %>
 <div> 
  <%= render :partial=> "queries/sidebar" %>
</div>
<div id="mainPanel">
  <h1>Edit Library Function</h1>
  <div class="top_border form_top_border">
      <div class="top_border_lower form_border_lower">
      </div>
    </div>

  <%= render 'form' %>
     <div class="bottom_border_lower relative">
      <div class="bottom_border">
      </div>
    </div>
</div>

</div>

app/views/library_functions/index.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {library_functions: true}}%>
 <div> 
  <%= render :partial=> "queries/sidebar" %>
</div>
<div id="mainPanel" >
  <h1>User Defined Library Functions</h1>
    <div class="top_border form_top_border">
      <div class="top_border_lower form_border_lower">
       </div>
    </div>

  <table class="simpleTable">
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
    </tr>

    <% @library_functions.each do |library_function| %>
      <tr>
        <td><%= link_to library_function.name, library_function %></td>
        <td><%= link_to 'Edit', edit_library_function_path(library_function), :class=> "btn tbbtn" %></td>
        <td><%= link_to '×', library_function, :data => { :confirm => 'Are you sure?'}, method: :delete, :class=> "btn alert" %></td>
      </tr>
    <% end %>
    </table>

  <%= link_to new_library_function_path, :class=> "btn primary m" do %><span>New Library function</span><% end %>
    <div class="bottom_border_lower relative">
      <div class="bottom_border">
        </div>
    </div>

</div>

app/views/library_functions/new.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {library_functions: true}} %>
 <div> 
  <%= render :partial=> "queries/sidebar" %>
</div>
<div id="mainPanel">
  <h1>Create New Library Function</h1>
    <div class="top_border form_top_border">
      <div class="top_border_lower form_border_lower">
      </div>
    </div>


  <%= render 'form' %>
  
  <%= link_to 'Back', library_functions_path, :class=>"btn second" %>
     <div class="bottom_border_lower relative">
      <div class="bottom_border">
      </div>
    </div>
</div>

app/views/library_functions/show.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {library_functions: true}} %>
 <div> 
  <%= render :partial=> "queries/sidebar" %>
</div>
<div id="mainPanel">
  <h1>Library Function Definition</h1>

  <p id="notice"><%= notice %></p>

  <table class="simpleTable">
    <div class="top_border form_top_border">
      <div class="top_border_lower form_border_lower">
      </div>
    </div>
    <tr>
      <th>Name</th>
      <td><%= @library_function.name %></td>
    </tr>
    <tr>
      <th>Definition</th>
      <td><pre><%= @library_function.definition %></pre></td>
    </tr>
  </table>
    <div class="bottom_border_lower relative">
      <div class="bottom_border">
      </div>
    </div>
</div>