config/routes.rb
QueryComposer::Application.routes.draw do

  post "scheduled_jobs/batch_query", :constraints => {:ip => /127.0.0.1/}

  devise_for :users

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  
  get "endpoints/refresh_endpoint_statuses"
  post 'queries/generate_query'

  resources :endpoints
  resources :library_functions
  resources :template_queries

  post "queries/clone_template"
  resources :queries do
    member do
      post 'execute'
      delete 'destroy'
      get 'log'
      get 'refresh_execution_results'
      get 'execution_history'
      get 'cancel'
      get 'cancel_execution'
      get 'builder'
      get 'builder_simple'
      get 'edit_code'
      get 'result'
    end
    collection do
      post 'execute_batch'
    end
  end
  
  
  resources :code_sets do

  end
  
  namespace :code_sets do
    get "by_type/:type", :action=>:by_type
  end
  
  root :to => 'queries#index'

  

end

app/views/admin/users.html.erb
<% content_for :head do -%>
<script type="text/javascript">
  var hQuery = hQuery || {};

  hQuery.promoteUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    $.post('<%= admin_promote_path %>', {'username': username}, function(data) {
      parentTd.html(data);
      parentTd.find('.demote').click(hQuery.demoteUser);
    });
    return false;
  };

  hQuery.demoteUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to remove admin rights from the currently logged in user' 
      +', this will cause you to immediately lose access to all admin functionality including this page.  ' 
      +'You will need to use another admin account to restore admin rights.  Are you sure you want to continue?');
      if (!response) return;
    }

    $.post('<%= admin_demote_path %>', {'username': username}, function(data) {
      parentTd.html(data);
      parentTd.find('.promote').click(hQuery.promoteUser);
    });
    return false;
  };

  hQuery.approveUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    $.post('<%= admin_approve_path %>', {'username': username}, function(data) {
      parentTd.html(data);
    });
  };

  hQuery.disableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();

    if (username == '<%= current_user.username %>') {
      var response = confirm('You are about to disable the currently logged in user' 
      +', this will cause you to immediately lose access and be logged out.  Are you sure you want to continue?');
      if (!response) return;
    }

    hQuery.disableEnableUser(1, username, parentTd)
  };
  hQuery.enableUser = function() {
    var username = $(this).data("username");
    var parentTd = $(this).parent();
    hQuery.disableEnableUser(0, username, parentTd)
  };
  hQuery.disableEnableUser = function(disabled, username, parentTd) {
    $.post('<%= admin_disable_path %>', {'username': username, 'disabled': disabled}, function(data) {
      parentTd.html(data);
      if (disabled == 1) parentTd.find('.disable').click(hQuery.enableUser);
      else parentTd.find('.enable').click(hQuery.disableUser);
    });
  };

  $(document).ready(function() {
    $('.promote').click(hQuery.promoteUser);
    $('.demote').click(hQuery.demoteUser);
    $('.approve').click(hQuery.approveUser);
    $('.enable').click(hQuery.disableUser);
    $('.disable').click(hQuery.enableUser);
    $(document).idleTimeout({
      inactivity: 300000,
      noconfirm: 10000,
      sessionAlive: false,
      alive_url: '/',
      redirect_url: '<%= destroy_user_session_path %>',
      logout_url: '/'
    });
  });
</script>
<% end -%>

<%= render partial: 'shared/tab_menu', locals: { selected: {admin: true}}%>

<div id="mainPanel">

<h1>Administer Users</h1>
<table class="simpleTable">
  <tr>
    <th>First Name</th>
    <th>Last Name</th>
    <th>Username</th>
    <th>Admin</th>
    <th>Approved</th>
    <th>Status</th>
  </tr>
  <% @users.each do |user| -%>
  <tr>
    <td><%= user.first_name %></td>
    <td><%= user.last_name %></td>
    <td><%= user.username %></td>
    <td>
      <% if user.admin? -%>
      Yes - <a href="#" class="demote" data-username="<%= user.username %>">remove admin rights</a>
      <% else -%>
      No - <a href="#" class="promote" data-username="<%= user.username %>">grant admin rights</a>
      <% end -%>
    </td>
    <td>
      <% if user.approved? -%>
      true
      <% else -%>
      <a href="#" class="approve" data-username="<%= user.username %>">approve</a>
      <% end -%>
    </td>
    <td>
      <a href="#" class="<%= (user.disabled?) ? 'disable' : 'enable'%>" data-username="<%= user.username %>"><%= (user.disabled?) ? 'disabled' : 'enabled'%></a>
    </td>
  </tr>
  <% end -%>
</table>

</div>