config/routes.rb
QueryComposer::Application.routes.draw do

  post "scheduled_jobs/batch_query", :constraints => {:ip => /127.0.0.1/}

  devise_for :users

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  
  get "endpoints/refresh_endpoint_statuses"
  post 'queries/generate_query'

  resources :endpoints
  resources :library_functions
  resources :template_queries

  post "queries/clone_template"
  resources :queries do
    member do
      post 'execute'
      delete 'destroy'
      get 'log'
      get 'refresh_execution_results'
      get 'execution_history'
      get 'cancel'
      get 'cancel_execution'
      get 'builder'
      get 'builder_simple'
      get 'edit_code'
      get 'result'
    end
    collection do
      post 'execute_batch'
    end
  end
  
  
  resources :code_sets do

  end
  
  namespace :code_sets do
    get "by_type/:type", :action=>:by_type
  end
  
  root :to => 'queries#index'

  

end

app/views/shared/_header.html.erb
<header>
  <div id="logo">
    <p><a href="/"><%= image_tag "hquery_header_logo.png", :alt => "hQuery logo"%></a></p>
    <p>User: <%= current_user.first_name.to_s %> <%= current_user.last_name.to_s %></p>
  </div>
  <%= yield :tabMenu %>
</header>

app/views/shared/_tab_menu.html.erb
<% content_for :tabMenu do -%>
<nav>
  <ul>
      <li class="<%=(selected[:queries]) ? ' selected' : ''%>" data-tab="queries"><%= link_to "Queries", queries_path %></li>
      <li class="<%=(selected[:template_queries]) ? ' selected' : ''%>" data-tab="template_queries" style="display:none"><%= link_to "Template Queries", template_queries_path %></li>
      <li class="<%=(selected[:library_functions]) ? ' selected' : ''%>" data-tab="library_functions" style="display:none"><%= link_to "Library Functions", library_functions_path %></li>
      <li class="<%=(selected[:help]) ? 'selected' : ''%>" data-tab="help"><a href="#">Help</a></li>
      <li class="<%=(selected[:account]) ? ' selected' : ''%>" data-tab="account"><%= link_to "Account", edit_user_registration_path(current_user) %></li>
      <li class="<%=(selected[:admin]) ? ' selected' : ''%>" data-tab="admin"><%= link_to "Admin", admin_users_path %></li>
      <li data-tab="logout"><%= link_to 'Logout', destroy_user_session_path%></li>

  </ul>
  </nav>
<% end %>

app/views/shared/_top_nav.html.erb
<div id="logOut">
  Welcome, <%= current_user.first_name.to_s %> <span class="sep">|</span>
  <a href="#">help</a> <span class="sep">|</span>
  <%= link_to 'account', edit_user_registration_path(current_user) %> <span class="sep">|</span>
  <% if current_user.admin? -%>
  <%= link_to 'admin', admin_users_path %> <span class="sep">|</span>
  <% end -%>
  <%= link_to 'logout', destroy_user_session_path%>
</div>