config/routes.rb
QueryComposer::Application.routes.draw do

  post "scheduled_jobs/batch_query", :constraints => {:ip => /127.0.0.1/}

  devise_for :users

  get "admin/users"
  post "admin/promote"
  post "admin/demote"
  post "admin/approve"
  post "admin/disable"
  
  get "endpoints/refresh_endpoint_statuses"
  post 'queries/generate_query'

  resources :endpoints
  resources :library_functions
  resources :template_queries

  post "queries/clone_template"
  resources :queries do
    member do
      post 'execute'
      delete 'destroy'
      get 'log'
      get 'refresh_execution_results'
      get 'execution_history'
      get 'cancel'
      get 'cancel_execution'
      get 'builder'
      get 'builder_simple'
      get 'edit_code'
      get 'result'
    end
    collection do
      post 'execute_batch'
    end
  end
  
  
  resources :code_sets do

  end
  
  namespace :code_sets do
    get "by_type/:type", :action=>:by_type
  end
  
  root :to => 'queries#index'

  

end

app/models/query.rb
require 'result_presenter'
require 'generated_result_presenter'

class Query < BaseQuery
  include Mongoid::Document

  embeds_many :executions, class_name: 'Execution', inverse_of: :query

  belongs_to :user
  
  before_save :generate_map_reduce # noop unless generated?
  
  def last_execution
    executions.desc(:time).first
  end

  def execute(endpoints, should_notify = false)
    # add an execution to the query with the current run time and if the user wants to be notified by email on completion
    execution = Execution.new(time: Time.now.to_i, notification: should_notify)
    self.executions << execution
    self.save!

    execution.execute(endpoints)
  end
  
  def generate_map_reduce
    if (self.generated?)
      map_function = ""
      map_template = ActionView::Base.new(QueryComposer::Application.paths['app/views'])
      map_template = map_template.render(:template => "queries/builder/_map_function", :handlers => [:erb], :formats => [:js], locals: { :query_structure => self.query_structure })
      self.map = prettify_generated_function(map_template)
    
      reduce_function = ""
      reduce_template = ActionView::Base.new(QueryComposer::Application.paths['app/views'])
      reduce_template = reduce_template.render(:template => "queries/builder/_reduce_function", :handlers => [:erb], :formats => [:js], locals: { :query_structure => self.query_structure })
      self.reduce = prettify_generated_function(reduce_template)
    end
  end

  def clone
    Query.new(self.attributes.except('_id'));
  end
  
  def init_query_structure!
    self.query_structure = {"find"=>{"and"=>[]}, "filter"=>{"and"=>[]}, "extract"=>{"selections"=>[], "groups"=>[]}}
  end
  
  def result_presenter
    if generated?
      GeneratedResultPresenter.new(title, last_execution.try(:aggregate_result))
    else
      ResultPresenter.new(title, last_execution.try(:aggregate_result))
    end
  end
  
  private
  
  # Note: This is not generic to all code; it assumes that all closing blocks are on their own line like we do within our generated code
  # TODO (agoldstein):  We should write comments in generated MapReduce code so a user can understand it, but strip it out when sending out to the gateway
  def prettify_generated_function function
    pretty_function = ""
    tab_count = 0
    function.each_line do |line|
      if (line =~ /^[\t   ]*function /) # Skip a line to make it easier to spot new functions
        pretty_function << "\n"
      end
      if !(line =~ /^[\t   ]*\n/) # Only include lines that consist of more than just tabs and spaces
        line = line.gsub("  ", '') # Erase all existing leading tabs
        if (line =~ /^[\t   ]*[\}\]\)]+.*[\{\[\(]+\n*/) # Indent less to print since we're closing a block, but leave tab_count the same since we're also opening one
          (tab_count-1).times { pretty_function << "  " }
        elsif (line =~ /[\{\[\(]\n*$/) # Indent further if we're opening some kind of block
          tab_count.times { pretty_function << "  " }
          tab_count += 1 
        elsif (line =~ /^[\t   ]*[\}\]\)]+;*\n*/) # Indent less if we're closing some kind of block
          tab_count -= 1 
          tab_count.times { pretty_function << "  " }
        else
          tab_count.times { pretty_function << "  " }
        end
        pretty_function << line
      end
    end
    
    return pretty_function
  end
end

app/controllers/queries_controller.rb
require 'stringio'
require 'net/http/post/multipart'

class QueriesController < ApplicationController
  # load resource must be before authorize resource
  load_resource exclude: %w{index log clone_template}
  authorize_resource
  before_filter :authenticate_user!

  # add breadcrumbs
  add_breadcrumb 'Queries', :queries_url
  add_breadcrumb_for_resource :query, :title, only: %w{edit show log execution_history builder builder_simple}
  add_breadcrumb_for_actions only: %w{edit new log execution_history builder builder_simple}

  creates_updates_destroys :query

  def index
    @queries = (current_user.admin?) ? Query.all : current_user.queries
  end

  def log
  end

  def show
    @endpoints = Endpoint.all
  end
  
  def edit
    if (@query.generated?) 
      @query = @query.clone
      @query.title = "#{@query.title} (cloned)"
      @query.generated = false;
      @query.save!
    end
    
    if (@query.map.nil?)
      @query.map = "function map(patient) {\r\n  \r\n}"
    end
    if (@query.reduce.nil?)
      @query.reduce = "function reduce(key, values) {\r\n  return Array.sum(values); \r\n}"
    end
  end

  def before_create
    @query.user = current_user
    @query.init_query_structure!
  end
  
  def after_create
    if @query.generated?
      redirect_to builder_query_path(@query)
    else
      redirect_to edit_query_path(@query)
    end
  end
  
  def before_update
    convert_to_hash(:query_structure)
  end

  def new
    template = params[:builder] ? "queries/builder": "queries/new"
    render :template=> template
  end

  def builder
     @endpoints = Endpoint.all
  end
  
  def result
    @presenter = @query.result_presenter
  end

  def execute
    endpoint_ids = params[:endpoint_ids]
    if (endpoint_ids && !endpoint_ids.empty?) 
      endpoint_ids = endpoint_ids.map! {|id| Moped::BSON::ObjectId(id)}
      endpoints = Endpoint.criteria.for_ids(endpoint_ids)

      notify = params[:notification]
      
      # execute the query, and pass in the endpoints and if the user should be notified by email when execution completes
      @query.execute(endpoints, notify)

      redirect_to :action => 'show'
    else
      flash[:alert] = "Cannot execute a query if no endpoints are provided."
      redirect_to :action => 'show'
    end
  end


  def execute_batch
    endpoint_ids = params[:endpoint_ids]

    if (endpoint_ids && !endpoint_ids.empty?)
      endpoint_ids = endpoint_ids.map! {|id| Moped::BSON::ObjectId(id)}
      endpoints = Endpoint.criteria.for_ids(endpoint_ids)

      notify = params[:notification]

      current_user.queries.each do |eachQuery|
        # execute the query, and pass in the endpoints and if the user should be notified by email when execution completes
        eachQuery.execute(endpoints, notify)
      end

      redirect_to :action => 'index'
    else
      flash[:alert] = "Cannot execute a query if no endpoints are provided."
      redirect_to :action => 'index'
    end
  end

  def cancel
    execution = @query.executions.find(params[:execution_id])
    execution.results.find(params[:result_id]).cancel
    redirect_to :action => 'show'
  end

  def cancel_execution
    @query.executions.find(params[:execution_id]).cancel
    redirect_to :action => 'show'
  end

  # This function is used to re-fetch the value of a query. Used to check the status of a query's execution results
  def refresh_execution_results
    if (@query.last_execution)
      @incomplete_results = @query.last_execution.unfinished_results.count > 0
      @incomplete_results ||= @query.last_execution.results.where(aggregated: false).count > 0
    else
      @incomplete_results = false
    end
    @query.reload
    respond_to do |format|
      format.js { render :layout => false }
    end
  end
  
  def clone_template
    @query = TemplateQuery.find(params[:template_id]).to_query
    @query.title = "#{@query.title} (cloned)"
    render :new
  end

  private

  def convert_to_hash(field)
    params[:query][field] = JSON.parse(params[:query][field]) if params[:query][field]
  end

end

app/helpers/queries_helper.rb
module QueriesHelper
  def jsonify(value)
    begin
      if value.class == Hash || value.class == Array || value.class == Moped::BSON::OrderedHash
        JSON.pretty_generate(value)
      else
        value
      end
    rescue
    return value
  end
  end
end

app/views/queries/_aggregate_results.erb
<% if @query.last_execution && @query.last_execution.aggregate_result %>
	<tr id="aggregate_results">
    	<th align='left' valign='top'>Aggregate Result</th>
    	<td>
			<table>
				<% @query.last_execution.aggregate_result.each do |key, value| %>
    			<% next if key=='_id' %>
    			<tr>
      				<td><code><%= key %>:</code></td>
      				<td><code><%= jsonify(value) %></code></td>
    			</tr>
    			<% end %>
			</table>
		</td>
	</tr>
<% end %>

app/views/queries/_debugger.html.erb
<% content_for :head do -%>
  <%= stylesheet_link_tag "debugger.css"%>
  <%= javascript_include_tag "ace_editor/ace" %>
  <%= javascript_include_tag "ace_editor/mode-javascript" %>
  <%= javascript_include_tag "debugger/records" %>

  <script type="text/javascript">
    $(document).ready(function() {
      hDebugger.initialize();
    });
    
    <%
      container = CoffeeScript.compile(Rails.root.join('app/assets/javascripts/builder/container.js.coffee').read, :bare=>true)
      reducer = CoffeeScript.compile(Rails.root.join('app/assets/javascripts/builder/reducer.js.coffee').read, :bare=>true)
      rules = CoffeeScript.compile(Rails.root.join('app/assets/javascripts/builder/rules.js.coffee').read, :bare=>true)
      generated_query_library_functions = "var queryStructure = queryStructure || {}; " + container + reducer + rules
    
      user_library_functions = ""
      @current_user.library_functions.each do |library_function|
        user_library_functions << library_function.definition
      end
    %>
    
    hDebugger.addLibraryFunctions(<%= raw generated_query_library_functions.to_json %>);
    hDebugger.addLibraryFunctions(<%= raw user_library_functions.to_json %>);
  </script>
<% end %>

<tr><td>Map Function</td>
  <td>
    <div id="map_container" class="debug_container">
      <div id="map_editor" class="debug_editor"></div>
      <textarea id="map_text" name="query[map]" class="hidden"><%= @query.map %></textarea>
    </div>
    <div id="map_error_panel" class="debug_error_panel">
      <p id="map_error_panel_text"></p>
    </div>
  </td>
</tr>
<tr><td>Reduce Function</td>
  <td>
    <div id="reduce_container" class="debug_container">
      <div id="reduce_editor" class="debug_editor"></div>
      <textarea id="reduce_text" name="query[reduce]" class="hidden"><%= @query.reduce %></textarea>
    </div>
    <div id="reduce_error_panel" class="debug_error_panel">
      <p id="reduce_error_panel_text"></p>
    </div>
  </td>
</tr>
<tr class="debug_output"><td>Map Output</td><td><table id="map_output"></table></td></tr>
<tr class="debug_output"><td>Reduce Output</td><td><table id="reduce_output"></table></td></tr>

app/views/queries/_query_details.html.erb
<% is_new = @query.title.nil? %>

<%= simple_form_for @query do |f| %>
<table class="simpleTable">
    <div class="top_border form_top_border">
      <div class="top_border_lower form_border_lower">
      </div>
    </div>
  <tr><td>Title</td><td><%= f.input_field :title, :disabled => @disabled, :class=> "entryField" %></td></tr>
  <tr><td>Description</td><td><%= f.input_field :description, :disabled => @disabled, :class=> "entryField" %></td></tr>
  <% if not is_new %>
    <tr><td>Filter</td><td><%= f.input_field :filter, :disabled => @disabled %></td></tr>
    <%= render :partial => "debugger" %>
  <% else %>
    <tr><td>Mode</td>
      <td>
        <%= f.radio_button :generated, true, :checked => false %> Graphical Builder
        <%= f.radio_button :generated, false, :checked => true %> Handwritten JavaScript (Advanced)
      </td>
    </tr>
  <% end %>
</table>
<div class="ctrl"> 
  <% if (not is_new) %>
    <span class="ctrl">
      <input id="debug_button" type="button" value="Debug" disabled="disabled" class="btn primary"></input>
    </span>
    <%= f.button :submit, :class => "btn primary m" if !@disabled %>
    <%= link_to 'Browse API', '/patientapi/index', :target => '_blank', :class => 'btn top' %>
    <%= link_to 'Cancel', @query, :class => "btn" %>
  <% else %>
    <%= f.button :submit, 'Continue', :class => "btn primary m" if !@disabled %>
    <%= link_to 'Cancel', queries_path, :class => "btn second" %>
  <% end %> 
    <div class="bottom_border_lower relative">
      <div class="bottom_border">
      </div>
    </div>
</div>
<% end %>

app/views/queries/_sidebar.html.erb
  <div id="links" class="paletteLink">
    <div class="border_color">
      <div class="border_edge">
        <div class="icons">
          <h1>Links</h1>
          	<ul>
	            <li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to "Template Queries", template_queries_path %></li>
	          	<li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to 'Query List', queries_path %></li>
	          	<li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to "Library Functions", library_functions_path %></li>
	          	<li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to 'Code Sets', code_sets_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/queries/_sidebarQ.html.erb
  <div id="links" class="paletteLink">
    <div class="border_color">
      <div class="border_edge">
        <div class="icons">
          <h1>Links</h1>
          	<ul>
	            <li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to "Template Queries", template_queries_path %></li>
	          	<li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to 'Query List', queries_path %></li>
	          	<li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to "Library Functions", library_functions_path %></li>
	          	<li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to 'Code Sets', code_sets_path %></li>
              <li><%= image_tag("linkIcon.png",{class:"linkcon"}) %><%= link_to 'Execution Log', log_query_path %></li>
          </ul>
        </div>
      </div>
    </div>
  </div>

app/views/queries/builder.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}} %>

<script>
  var query = new queryStructure.Query();

  query.rebuildFromJson(<%= (@query.query_structure || {}).to_json.html_safe %>);

  $(document).ready(function(){
    $("#icon_demo").draggable({helper:"clone",opacity:"1", refreshPostions:true , start:function(){$(this).data("item",new queryStructure.And(null, [], "demographics"))}});
  // $("#icon_history").draggable({helper:"clone",opacity:"1", start:function(){$(this).data("item",new queryStructure.And(null, [], "history"))}});
  // $("#icon_conditions").draggable({helper:"clone",opacity:"1", start:function(){$(this).data("item",new queryStructure.And(null, [], "conditions"))}});
    $("#icon_observations").draggable({helper:"clone",opacity:"1", start:function(){$(this).data("item",new queryStructure.And(null, [], "observations"))}});
    $("#icon_treatments").draggable({helper:"clone",opacity:"1", start:function(){$(this).data("item",new queryStructure.And(null, [], "treatments"))}});
    $("#icon_raw_javascript").draggable({helper:"clone",opacity:"1", start:function(){$(this).data("item",new queryStructure.And(null, [], "rawJavascript"))}});

    $("#find > .conditional_editor").AndContainerUI({container:query.find});
    $("#filter > .conditional_editor").AndContainerUI({container:query.filter});
    $("#extract").ExtractUI();
  });


  function updateQuery(){
    $.ajax(
     {type:"PUT", 
      url:"/queries/<%= @query._id %>", 
      data:{"query":{"query_structure":JSON.stringify(query.toJson()), "id":"<%= @query._id %>"}}, 
      success:function(data){}})
  }


  $("body, #displayWrapper, #iconWrapper").droppable({
    greedy:true,
    accept:function(ui){
      return $(ui).data().ItemUI || $(ui).data().AndContainerUI || $(ui).data().OrContainerUI || $(ui).data().ExtractItemUI;
    },
    drop:function(element, ui){
      var item = $(ui.draggable).data().ItemUI || $(ui.draggable).data().AndContainerUI || $(ui.draggable).data().OrContainerUI || $(ui.draggable).data().ExtractItemUI;
      item._remove();
    }
  });




  $(document).ready(function () {
    var $vi = $("#variablesIcons");
    var icons_offsetTop = $vi.offset().top - parseFloat($vi.css("margin-top").replace(/auto/,0));
    var $ffe = $("#ffeWrapper");
    var icons_bot = $vi.height() - icons_offsetTop;

    $(window).scroll(function () {
      var icons_bot = $vi.height() - icons_offsetTop;
      var scrollTop = $(document).scrollTop();
      var delta = $ffe.height()  - scrollTop;
      var scrollLeft = $(document).scrollLeft();
        

      

      if (scrollTop >= icons_offsetTop) {
        if (delta - icons_bot < 1 ) {
            $vi.addClass("bottom");
            $vi.removeClass("fixed");
        } else {
          $vi.addClass("fixed"); 
          $vi.removeClass("bottom");
          
        }
      } else {
        $vi.removeClass("fixed");
      }
    }); 
  });

 </script>
  
  
  <script id="dateDetailsTemplate" type="text/x-jquery-tmpl"> 
    <div class="dateFieldset">
      <label>${$data.dateDescriptor || "recorded from"}</label>
      <span class="date">
        <label>Start</label>
        <input type="text" class="datePicker" size="11" value="${startDate}" name="startDate"/> 
      </span>
     <!-- <span class="sep">-</span> -->
      <span class="date">
        <label>End</label>
        <input type="text" class="datePicker" size="11" value="${endDate}" name="endDate"/>
      </span>
    </div>
  </script> 
  
  <script id="detailsDialogTemplate" type="text/x-jquery-tmpl">
    <form>  
    <div>

    {{if descriptor && descriptor.options}}
    <select name="descriptorLabel">
      {{each(index,item) descriptor.options}}
        <option value="${item.value}">${item.label}</option>
      {{/each}}
    </select>
    {{/if}}
    <label>${descriptor.valueText}</label>

    
    {{if variability && variability.options }}
      <select name="variabilityLabel" id="variabilityLabel">
      {{each(index,item) variability.options}}
        <option value="${item.value}">${item.label}</option>
      {{/each}}
      </select>
    {{/if}}
    {{if variability && variability.minValue}}
    <input type="text" size="5" value="${variability.minValue}" name="variabilityMin" id="variabilityMin" />
    <span class="sep">-</span>
    <input type="text" size="5" value="${variability.maxValue}" name="variabilityMax" id="variabilityMax" />
    {{/if}}
    </div>
    {{tmpl "#dateDetailsTemplate"}}
    <div class="dlgButtons">
      <input type="button" value="save" id="detailsSaveBtn"/>
      <input type="button" value="cancel" id="detailsCancelBtn"/>
    </div>
    </form>
    
  </script>
  
  
  
<%= render partial: 'execution_popup', locals: { endpoints: @endpoints, button_id: 'execute-button' } %>

<div id="queryInfo">
  <% if session[:pmn_session_data] %>
  <%= link_to("#", id: "execute-button", class: "btn primary") do %><span>Execute</span><% end %>
  <% end %>
  <span class="sep">|</span> <%= link_to("Query Definition", query_path, class:"ctrl") %>
  <input class="searchfield" type="text" value="Search..." onfocus="if (this.value == 'Search...') {this.value = '';}" onblur="if (this.value == '') {this.value = 'Search...';}" />
  <h1><%= @query.title %></h1>
  <h2><%= @query.description %></h2>
</div>

<div id="ffeWrapper">
  <div id="variablesIcons" class="palette">
    <div class="border_color">
      <div class="border_edge">
        <div class="icons">
          <h1 title="Drag the variables into 'find', 'filter', or 'extract' to create a query">variables</h1>
          <ul>
            <li title="Drag this variable to query by demographic information including: Age, Race, Gender, Martial Status, Religious Affiliation, Occupation, Social history, and Insurance">
              <%= image_tag("icon_demo.png",{class:"demo", id:"icon_demo"}) %>demographics
            </li>
            <li title="Drag this variable to query by health history including: Advanced directives, Support, and Family History">
              <%= image_tag("icon_history.png",{class:"demo", id:"icon_history"}) %>health history
            </li>
            <li title="Drag this variable to query by conditions including: Diagnosis Results and Conditions">
              <%= image_tag("icon_conditions.png",{class:"demo", id:"icon_conditions"}) %>conditions
            </li>
            <li title="Drag this variable to query by observations including: Functional status, Allergies, and Vital Signs">
              <%= image_tag("icon_observations.png",{class:"demo", id:"icon_observations"}) %>observations
            </li>
            <li title="Drag this variable to query by treatments including: Medications, Immunizations, Medical Equipment, Procedures, and Encounters">
              <%= image_tag("icon_treatments.png",{class:"demo", id:"icon_treatments"}) %>treatments
            </li>
            <li title="Drag variables in this field to type in raw JavaScript">
              <%= image_tag("icon_rawJavascript.png",{class:"demo", id:"icon_raw_javascript"}) %>javascript
            </li>
          </ul>
        </div>
      </div>
    </div>
  </div><!-- end #variablesPalette -->
  <div id="workspace">  
    <div id="find-filter-extract">
      <div class="top_border">
        <div class="top_border_lower">
        </div>
      </div>
      <div title="Drag variables in this field to establish a target population for the query" id="find" class="querySection">
        <h1>find</h1>
        <div class="conditional_editor"></div>
        <div class="bottom_border_lower">
          <div class="bottom_border">
          </div>
        </div>
      </div>

      <div title="Drag variables to filter the results of the query" id="filter" class="querySection">
        <h1>filter</h1>
        <div class="conditional_editor"></div>
        <div class="bottom_border_lower">
          <div class="bottom_border">
          </div>
        </div>
      </div>

      <div title="Drag variables here to pull specific information from the records" id="extract" class="querySection">
        <h1>extract</h1>
        <div class="extract_editor"></div>
        <div class="bottom_border_lower">
          <div class="bottom_border">
          </div>
        </div>
      </div>
    </div><!-- end #find-filter-extract -->

  </div><!-- end #workspace -->
</div>

<div id="displayIcons" class="palette">
  <div class="border_color">
    <div class="border_edge">
      <div class="icons">
        <h1 title="Drag the display variables to specify how the query results are displayed">display</h1>
          <ul>
            <li title="Drag this variable to display the query results by frequency">
              <%= image_tag("icon_freq.png") %>frequency
            </li>
            <li title="Drag this variable to display the query results by location">
              <%= image_tag("icon_location.png") %>location
            </li>
            <li title="Drag this variable to display the query results over time">
              <%= image_tag("icon_time.png") %>time
            </li>
          </ul>
      </div>
    </div>
  </div>
</div><!-- end #displayPalette -->


<div id="analyze_workspace" title="Drag display variables here to specify how to display the results" >
  <div id="analyze" class="querySection">
    <h1>analyze</h1>
    <div class="conditional_editor">
    </div>
    <div class="bottom_border_lower">
      <div class="bottom_border">
      </div>
    </div>
  </div>
</div>
<div id="detailDialog" style="position:absolute;display:none">
</div>
<div id="otherside">
  <div id="stats">
    <h1></h1>
  </div>

  <div id="trash">
  </div>

  <div id="connectors">
    <h1></h1>
  </div>
</div>

app/views/queries/edit.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}}%>
 <div> 
  <%= render :partial=> "sidebar" %>
</div>

<div id="mainPanel">
  <h1>Editing Query</h1>
  <%= render :partial => "query_details" %>
</div>

app/views/queries/edit_code.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}}%>

<div id="mainPanel">

  <h1>Editing Query</h1>
  <%= render :partial=>"query_details" %>
  
</div>

app/views/queries/index.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}}%>
 <div> 
  <%= render :partial=> "sidebar" %>
</div>
<div id="mainPanel" >
  <h1>Queries</h1>
    <div class="top_border">
      <div class="top_border_lower">
        </div>
    </div>
  <table class="simpleTable"> 
    <% if @queries.size %>
    <tr>
      <th>Title</th>
      <th>Description</th>
      <th></th>
      <th>Status</th>
    </tr>
    <% end %>
    <% @queries.asc(:description).each do |query| %>
    <tr>
      <td><%= link_to query.title, query_path(query.id) %></td>
      <td><%= query.description %></td>
      <td><% if (query.generated?) %>
      <%= link_to 'Builder', builder_query_path(query.id) %>
      <% else %>
      <%= link_to 'Advanced Edit', { :action => 'edit', :id => query.id }, :method => :get, id: 'edit' %>
      <% end %>
      <td>
        <% if (not query.last_execution) %>
          no executions
        <% else %>
          <% query.last_execution.status.each_pair do |status, count| %>
            <% if (status != query.last_execution.status.keys.first) %>,<% end %>
            <%= status %>
            (<%= count.to_s + " of " + query.last_execution.results.length.to_s%>)
          <% end %>
        <% end %>
      </td>
      <td><%= button_to '×', {:action=>'destroy', :id=>query.id}, :class=>"btn alert", :method=>:delete, :data => {:confirm=>'Are you sure you wish to delete the query ' + query.title} %></td>
    </tr>
    <% end %>
  </table>

  <%= render partial: 'execute_all_popup', locals: { endpoints: Endpoint.all, button_id: 'execute-all-button' } %>

  <%= link_to(new_query_path, class: "btn primary m") do %><span>Add Query</span><% end %>
  <% if !current_user.admin %>
    <button id="execute-all-button" class="btn primary">Execute All</button>
  <% end %>

  <div class="bottom_border_lower relative">
    <div class="bottom_border">
     </div>
  </div>

</div>

app/views/queries/log.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}}%>

<div> 
  <%= render :partial=> "sidebar" %>
</div>
<div id="mainPanel">
  <h1>Query Execution Log</h1>
  <h2>Query: <%= link_to @query.title, query_path %></h2>

  <table class="simpleTable">
    <tr>
    <th colspan="2">Time</th>
    <th>Result</th>
  </tr>
  <% @query.executions.each do |event| %>
    <tr>
      <td><%= Time.at(event.time).strftime("%m/%d/%Y") %></td>
      <td><%= Time.at(event.time).strftime("%I:%M%p") %></td>
      <% begin %>
      <td><pre><%= JSON.pretty_generate(event.aggregate_result) %></pre></td>
      <% rescue %>
      <td><pre><%= event.aggregate_result %></pre></td>
      <% end %>
    </tr>
  <% end %>
  </table>
  
  <p><%= link_to 'Back to Query', query_path %></p>
</div>

app/views/queries/new.html.erb
<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}}%>
 <div> 
  <%= render :partial=> "sidebar" %>
</div>
<div id="mainPanel">
  <h1>Create New Query</h1>
  <%= render :partial=>"query_details" %>
</div>

app/views/queries/refresh_execution_results.js.erb
<% if not @incomplete_results %>
  clearInterval(queryInfoRefreshInterval);
<% end %>
$("#execution_results").html("<%= escape_javascript(render :partial => 'execution_results', :locals => { :query => @query }) %>");
$("#aggregate_results").replaceWith("<%= escape_javascript(render :partial => 'aggregate_results', :locals => { :query => @query }) %>");

app/views/queries/result.html.erb
<% content_for :head do -%>
  <script type="text/javascript">
    $(document).ready(function() {
      HQuery.drawChart("<%= params[:type] %>", "<%= @presenter.title %>",
                      <%= raw @presenter.key_javascript_array %>,
                      <%= @presenter.value_javascript_array %>);
    });
  </script>
<% end -%>

<%= render partial: 'shared/tab_menu', locals: { selected: {queries: true}}%>

 <div> 
  <%= render :partial=> "sidebar" %>
</div>
<div id="mainPanel">

  <h1>Result</h1>
  <div id="chart"></div>

  <p><%= link_to 'Query List', queries_path %> <span class="sep">|</span> <%= link_to 'Event Log', log_query_path %> </p>
</div>